image:
  repository: mosesade/nodejs-service:${{ env.SHORT_SHA }}
  tag: 1679a2f
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 2222
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false