image:
  repository: mosesade/nodejs-service:${{ env.SHORT_SHA }}
  tag: aaf1d2d
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 2222
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false