securepassword123name: Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Deploy to Remote Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /home/${{ secrets.SERVER_USER }} || exit
            docker pull ghcr.io/${{ github.repository }}:latest
            docker stop node-app || true
            docker rm node-app || true
            docker run -d -p 3000:3000 --name node-app \
              -e USERNAME=${{ secrets.DOCKER_USERNAME }} \
              -e PASSWORD=${{ secrets.DOCKER_PASSWORD }} \
              -e SECRET_MESSAGE=${{ secrets.SECRET_MESSAGE }} \
              ghcr.io/${{ github.repository }}:latest