name: Deploy Node.js App

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    name: Unit testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set Short SHA
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Static code Analysis
        run: npm run lint

      #- name: Build project
      #  run: |
      #    npm start || echo "Error: no test specified\" && exit 1"

      - name: Build Docker Image
        run: |
          docker build -t mosesade/nodejs-service:${{ env.SHORT_SHA }} .

      - name: Security scan of Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: mosesade/nodejs-service:${{ env.SHORT_SHA }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Login to DockerHub
        run: |
          echo echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Image to DockerHub
        run: |
          docker push mosesade/nodejs-service:${{ env.SHORT_SHA }}